### ISSUE TITLE
arguments -t  or -c not recognized

### ISSUE THREAD

**Issue by unalignedcoder** [Exceen/4chan-downloader#43]
There seem to be a contradiction between instructions and reality

![Untitled](https://github.com/Exceen/4chan-downloader/assets/16850566/14b67d44-7e3c-4f80-88dc-122c1689303c)

I really wanted to use that `-t `argument but it won't let me.

**Comment by HelpSeeker** [comment]
Did you download the zip from the release page? Because that version is almost 5 years old by now.

**Comment by unalignedcoder** [comment]
> 

Okay where from then kind sir

**Comment by onioneffect** [comment]
Code -> Download ZIP

**Comment by unalignedcoder** [comment]
It works as intended now, but why does it create two folders from the same thread, one in `/downloads` and the other in `/new`?

**Comment by onioneffect** [comment]
> It works as intended now, but why does it create two folders from the same thread, one in `/downloads` and the other in `/new`?

This is exactly what the author intended: https://github.com/Exceen/4chan-downloader/issues/34#issuecomment-1089912251

---

This is unrelated, but I have noticed a bug that causes files to be downloaded both to `downloads/` and `new/`, creating duplicates. I think (?) it was introduced by one of my changes because it didn't happen before I ever contributed to the project. This is a subject for a whole new ticket.

**Comment by Exceen** [comment]
> It works as intended now, but why does it create two folders from the same thread, one in `/downloads` and the other in `/new`?

If you delete a file in the `/downloads` folder, the script handles this situation as if the file was never downloaded at all. That means that if the file doesn't exist in `/new` folder either, it will be downloaded into both folders again. If you only delete the file in the `/new` folder, nothing happens at all.

The reason for this behavior is that I wanted a full archive of a thread (which is inside the `/downloads` folder) and additionally to that I wanted to just keep the files I actually want to keep and remove the rest.

The `/downloads` folder basically just memorizes which files have already been downloaded so that the script can determine which files in the thread are new and still need to be downloaded. In theory you could just save a list of already downloaded files into a json-file instead of storing the full file in the `/downloads` folder.

**Comment by unalignedcoder** [comment]
I am not sure if this is the behavior. I didn't delete any files, yet this thread had all its content duplicated from the start:

![image](https://github.com/Exceen/4chan-downloader/assets/16850566/d559ebae-6d67-49ed-bc4a-4245a54e4b9b)
![image](https://github.com/Exceen/4chan-downloader/assets/16850566/2f73d170-a514-4d7b-8d89-4fab5dc20108)

That's a 200mb folder twice. If the /downloads folder is used only for reference, perhaps it could use the thumbnails, instead of the full file? And not be called 'downloads'...?

**Comment by unalignedcoder** [comment]
As a quick workaround, I've added the `-b --backup` argument:

![image](https://github.com/Exceen/4chan-downloader/assets/16850566/7a11e4c6-9352-4b87-841a-769e387e89e2)
![image](https://github.com/Exceen/4chan-downloader/assets/16850566/b81cc662-d5f2-45ad-aa63-a6f38def606e)

without the `-b`, it only saves images in `/downloads`

**Comment by Exceen** [comment]
> That's a 200mb folder twice. Is this intentional? If the /downloads folder is used only for reference, perhaps it could use the thumbnails, instead of the full file?

This is intended, yes.


> As a quick workaround, I've added the `-b --backup` argument:
> 
> without the `-b`, it only saves images in `/downloads`

I might push something later to omit the `/new` folder.

**Comment by Exceen** [comment]
added `--no-new-dir` argument
